
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Cam
 */
public class RecipesPanel extends javax.swing.JPanel {
    private MealAPI.MealResponse response;
    /**
     * Creates new form RecipesPanel
     */
    public RecipesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        mealImg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taInstructionsAndTutorial = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        randomRecipeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        savedRecipesBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(400, 32767));
        helpBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        searchBar = new javax.swing.JTextField();
        searchRecipeIngredient = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelCategory = new javax.swing.JLabel();
        saveRecipeLabel = new javax.swing.JLabel();
        yesSaveRecipeBtn = new javax.swing.JButton();
        youtubeLabel = new javax.swing.JLabel();
        yesSaveRecipeBtn1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultsList = new javax.swing.JList<>();

        jScrollPane1.setViewportView(ingredientList);

        taInstructionsAndTutorial.setEditable(false);
        taInstructionsAndTutorial.setColumns(20);
        taInstructionsAndTutorial.setRows(5);
        taInstructionsAndTutorial.setWrapStyleWord(true);
        taInstructionsAndTutorial.setMinimumSize(new java.awt.Dimension(13, 75));
        jScrollPane2.setViewportView(taInstructionsAndTutorial);

        jToolBar1.setRollover(true);

        randomRecipeButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        randomRecipeButton.setText("Get Random Recipe");
        randomRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomRecipeButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(randomRecipeButton);
        jToolBar1.add(jSeparator1);

        savedRecipesBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        savedRecipesBtn.setText("Saved Recipes");
        savedRecipesBtn.setFocusable(false);
        savedRecipesBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        savedRecipesBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        savedRecipesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedRecipesBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(savedRecipesBtn);
        jToolBar1.add(filler1);

        helpBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        helpBtn.setText("Help");
        helpBtn.setFocusable(false);
        helpBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helpBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(helpBtn);
        jToolBar1.add(jSeparator3);

        searchBar.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        jToolBar1.add(searchBar);

        searchRecipeIngredient.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        searchRecipeIngredient.setText("Search");
        searchRecipeIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecipeIngredientActionPerformed(evt);
            }
        });
        jToolBar1.add(searchRecipeIngredient);

        saveRecipeLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        saveRecipeLabel.setText("Save Recipe?");

        yesSaveRecipeBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        yesSaveRecipeBtn.setText("Go to");

        youtubeLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        youtubeLabel.setText("Youtube Link");

        yesSaveRecipeBtn1.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        yesSaveRecipeBtn1.setText("Yes");

        resultsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resultsListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(resultsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mealImg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveRecipeLabel)
                                    .addComponent(youtubeLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(yesSaveRecipeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(yesSaveRecipeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveRecipeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesSaveRecipeBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(youtubeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesSaveRecipeBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mealImg, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void displayMeal(MealAPI.MealData data){
        mealImg.setIcon(new ImageIcon(data.loadImage().getScaledInstance(250, 250, BufferedImage.SCALE_SMOOTH)));
        ingredientList.setListData(data.getIngredients());
        String instructionsAndTutorial = data.getInstructions() + " Youtube tutorial: " + data.strYoutube;
        taInstructionsAndTutorial.setText(instructionsAndTutorial);
        labelID.setText("Meal ID: " + data.idMeal);
        labelName.setText("Meal Name: " + data.strMeal);
        labelCategory.setText("Category: " + data.strCategory);
    }
    
    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchRecipeIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecipeIngredientActionPerformed
        response = MealAPI.searchMeal(searchBar.getText());
        if (response != null && response.meals != null) {
            resultsList.setListData(response.getNames());
        } else {
            // Handle no results found or error
            resultsList.setListData(new String[0]);
        }
    }//GEN-LAST:event_searchRecipeIngredientActionPerformed

    private void randomRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomRecipeButtonActionPerformed
        MealAPI.MealData data = MealAPI.getRandom();
        displayMeal(data);
        
        //Opens the image in default browser
        //        try {
        //            Desktop.getDesktop().browse(new URI(data.strMealThumb));
        //        } catch (URISyntaxException ex) {
        //            Logger.getLogger(RecipesPanel.class.getName()).log(Level.SEVERE, null, ex);
        //        } catch (IOException ex) {
        //            Logger.getLogger(RecipesPanel.class.getName()).log(Level.SEVERE, null, ex);
        //        }
    }//GEN-LAST:event_randomRecipeButtonActionPerformed

    private void resultsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resultsListValueChanged
        if (!evt.getValueIsAdjusting()) {
            String selectedMealName = resultsList.getSelectedValue();
            MealAPI.MealData selectedMeal = response.getMeal(selectedMealName);
        if (selectedMeal != null) {
            displayMeal(selectedMeal);
        }
     }
    }//GEN-LAST:event_resultsListValueChanged

    private void savedRecipesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedRecipesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savedRecipesBtnActionPerformed

    private void showSavedRecipes() {
        JOptionPane.showMessageDialog(this, "Saved recipes functionality not implemented yet.");
    }

    private void showHelp() {
        JOptionPane.showMessageDialog(this, "Help functionality not implemented yet.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton helpBtn;
    private javax.swing.JList<String> ingredientList;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel mealImg;
    private javax.swing.JButton randomRecipeButton;
    private javax.swing.JList<String> resultsList;
    private javax.swing.JLabel saveRecipeLabel;
    private javax.swing.JButton savedRecipesBtn;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchRecipeIngredient;
    private javax.swing.JTextArea taInstructionsAndTutorial;
    private javax.swing.JButton yesSaveRecipeBtn;
    private javax.swing.JButton yesSaveRecipeBtn1;
    private javax.swing.JLabel youtubeLabel;
    // End of variables declaration//GEN-END:variables
}
