/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Cam
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        veganOn = new javax.swing.JButton();
        veganOff = new javax.swing.JButton();
        veganLabel = new javax.swing.JLabel();
        nutFreeLabel = new javax.swing.JLabel();
        nutFreeOn = new javax.swing.JButton();
        nutFreeOff = new javax.swing.JButton();
        glutenFreeLabel = new javax.swing.JLabel();
        glutenFreeOn = new javax.swing.JButton();
        glutenFreeOff = new javax.swing.JButton();
        lactoseFreeLabel = new javax.swing.JLabel();
        lactoseFreeOn = new javax.swing.JButton();
        lactoseFreeOff = new javax.swing.JButton();
        dietaryRestrictionsLabel = new javax.swing.JLabel();

        setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N

        veganOn.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        veganOn.setText("On");

        veganOff.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        veganOff.setText("Off");
        veganOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veganOffActionPerformed(evt);
            }
        });

        veganLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        veganLabel.setText("Vegan");

        nutFreeLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        nutFreeLabel.setText("Nut Free");

        nutFreeOn.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        nutFreeOn.setText("On");

        nutFreeOff.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        nutFreeOff.setText("Off");
        nutFreeOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutFreeOffActionPerformed(evt);
            }
        });

        glutenFreeLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        glutenFreeLabel.setText("Gluten-free");

        glutenFreeOn.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        glutenFreeOn.setText("On");

        glutenFreeOff.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        glutenFreeOff.setText("Off");

        lactoseFreeLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lactoseFreeLabel.setText("Lactose-free");

        lactoseFreeOn.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lactoseFreeOn.setText("On");

        lactoseFreeOff.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lactoseFreeOff.setText("Off");

        dietaryRestrictionsLabel.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        dietaryRestrictionsLabel.setText("   Change your dietary resctrictions!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(veganLabel)
                            .addComponent(glutenFreeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(veganOn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(glutenFreeOn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(glutenFreeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lactoseFreeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(veganOff, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(nutFreeLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nutFreeOn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lactoseFreeOn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lactoseFreeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutFreeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(dietaryRestrictionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(dietaryRestrictionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veganLabel)
                    .addComponent(veganOn)
                    .addComponent(veganOff)
                    .addComponent(nutFreeLabel)
                    .addComponent(nutFreeOff)
                    .addComponent(nutFreeOn))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glutenFreeLabel)
                    .addComponent(glutenFreeOn)
                    .addComponent(glutenFreeOff)
                    .addComponent(lactoseFreeLabel)
                    .addComponent(lactoseFreeOn)
                    .addComponent(lactoseFreeOff))
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void veganOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veganOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veganOffActionPerformed

    private void nutFreeOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutFreeOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutFreeOffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dietaryRestrictionsLabel;
    private javax.swing.JLabel glutenFreeLabel;
    private javax.swing.JButton glutenFreeOff;
    private javax.swing.JButton glutenFreeOn;
    private javax.swing.JLabel lactoseFreeLabel;
    private javax.swing.JButton lactoseFreeOff;
    private javax.swing.JButton lactoseFreeOn;
    private javax.swing.JLabel nutFreeLabel;
    private javax.swing.JButton nutFreeOff;
    private javax.swing.JButton nutFreeOn;
    private javax.swing.JLabel veganLabel;
    private javax.swing.JButton veganOff;
    private javax.swing.JButton veganOn;
    // End of variables declaration//GEN-END:variables
}
